sudo: false

language: node_js

node_js:
  - "7"
  - "8"

branches:
  only:
    - master

notifications:
  email:
    on_failure: change
    on_success: change

cache:
   # TODO: Use npm once functions runtime is updated to a node verion with lock files
  yarn: true
  directories:
    - node_modules # NPM packages

install:
  # TODO: Use npm again functions runtime is updated to a node verion with lock files
  - yarn install

script:
  - npm run lint
  # - npm run test
  - npm run release

addons:
  code_climate:
    repo_token: 2b32652090b39c2cc95f0ea3ca3e2c7ff452b75388a81f0f4cfacbce4588f6e6
